/**
 * Expected Props
 * Object char: a role playing game character with the following fields  
 *  {
 *      String or Integer id: THe character's ID in the database.
 *      String firstName: The character's given name,
 *      String lastName: The character's family name,
 *      String class: What the character is, e.g., Fighter, Wizard, Rogue
 *      Integer level: How experienced the character is.
 *  }
 * timestamp: String, generated by Time.now()
 * cool: String; either "cool" or "" used to tell which version of the card to load.
 */

 import React from 'react';
 import {Link} from 'react-router-dom';
 import { numberSuffix, capitalize } from "../helpers";


 const CharCard = (props) => {
     const {char, timestamp, cool} = props;

      return (
        <div
          className={`char-snippet ${cool === true ? 'cool' : '' }`}
          key={`${char.firstName}${timestamp}${char.lastName}${char.id}`}
          value={`${char.id}`}
        >
          <div className={`char-snippet-name ${cool === true ? 'cool' : '' }`}>
            {char.firstName} {char.lastName}
          </div>
          <div className={`char-snippet-class ${cool === true ? 'cool' : '' }`}>
            {char.level}
            {numberSuffix(char.level)} level {capitalize(char.class)}
          </div>

          <div className={`char-thumb-container ${cool === true ? 'cool' : '' }`}>
            <img
              className={`char-thumb ${cool === true ? 'cool' : '' }`}
              src={
                char.image
                  ? `${char.image}`
                  : "http://www.clarkegroup.co.uk/wp-content/uploads/2014/10/placeholder-employee.jpg"
              }
            />
          </div>
          <Link to={`/characters/${char.id}`} className={`link-button ${cool === true ? 'cool' : '' }`}>
            VIEW PROFILE
          </Link>
        </div>
      );
 }

 export default CharCard;